package pkg

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"regexp"
)

const (
	url = "https://raw.githubusercontent.com/android/platform_frameworks_base/master/core/java/android/view/KeyEvent.java"
)

func main() {
	resp, err := http.Get(url)
	if err != nil {
		fmt.Printf("无法获取 KeyEvent.java: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Printf("无法获取 KeyEvent.java (HTTP %d)\n", resp.StatusCode)
		os.Exit(1)
	}

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("读取响应失败: %v\n", err)
		os.Exit(1)
	}

	regex := regexp.MustCompile(`public static final int (KEYCODE_[^\s]+)\s*=\s*([0-9]+);`)
	matches := regex.FindAllStringSubmatch(string(body), -1)

	fmt.Println("# Generated by `go run main.go`")
	fmt.Println("# KeyEvent.java Copyright (C) 2006 The Android Open Source Project")
	fmt.Println("")

	for _, match := range matches {
		fmt.Printf("%s: %s\n", match[1], match[2])
	}
}
